<?php

namespace vaersaagod\muxmate\models;

use Craft;
use craft\base\Model;
use craft\helpers\ConfigHelper;

use yii\base\InvalidConfigException;

/**
 * Mux Signing Key model
 */
class MuxSigningKey extends Model
{

    public string $id;

    public string $privateKey;

    public int $minExpirationTime = 300;

    /**
     * @throws InvalidConfigException
     */
    public function setAttributes($values, $safeOnly = true): void
    {
        if (isset($values['minExpirationTime'])) {
            $values['minExpirationTime'] = ConfigHelper::durationInSeconds($values['minExpirationTime']);
        }
        parent::setAttributes($values, $safeOnly); // TODO: Change the autogenerated stub
    }

    protected function defineRules(): array
    {
        return array_merge(parent::defineRules(), [
            // ...
        ]);
    }
}
